---
- hosts: webservers
  sudo: yes
  tasks:
          - name: install apache2
            apt:
                    name: apache2
                    state: present
                    
 run command,
 ansible-playbook apache2.yml --ask-sudo-pass
